org.gradle.jvmargs=-Xmx3G
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.parallel=true
org.gradle.debug=false

modGroup=com.ldtteam
modVersion=0.0.2-ALPHA
modId=per_viam_invenire

javaVersion=21
useJavaToolChains=true

forgeVersion=21.0.+
minecraftVersion=1.21
exactMinecraftVersion=1.21
additionalMinecraftVersions=1.21.1
usesParchment=true
parchmentMappingsVersion=2024.07.07
parchmentMinecraftVersion=1.21

jimfs_version=1.2

shadowRenamedNamespaces=

githubUrl=https://github.com/ldtteam/PerViamInvenire
gitUrl=https://github.com/ldtteam/PerViamInvenire.git
gitConnectUrl=https://github.com/ldtteam/PerViamInvenire.git
projectUrl=https://www.curseforge.com/minecraft/mc-mods/perviaminvenire

usesCurse=true
curseId=449945

usesDatagen=true
usesResourceDataExpansionFromProjectKeys=true

extendDefaultSourceSetConfiguration=true
additionalSourceSets=gametest
gametestConfigurationDependencies=minecraft;
gametestSourceSetDependencies=main;api

librarySourceSets=gametest