modLoader="javafml" #mandatory
loaderVersion="[28,)" #mandatory (26 is current forge version)
license="LGPL v3"
[[mods]] #mandatory
modId="per_viam_invenire" #mandatory
version="${version}" #mandatory
displayName="Per Viam Invenire" #mandatory
authors=["OrionOnline", "LDTTeam"] #optional
description='''
Cached highspeed pathfinding for Minecraft.
'''
