repositories {
    mavenLocal()
}

runs {
    gameTestServer {
        modSource sourceSets.gametest
    }

    gameTestClient {
        configure 'client'

        modSource sourceSets.gametest
    }

    renderDoc {
        configure 'client'

        renderDoc {
            enabled true
        }
    }
}

dependencies {
    gametestLibrary ("com.google.jimfs:jimfs:${jimfs_version}") {
        transitive = false
    }
}